export default[
    {
        id:1,
        name:'Programming',
        icon:'/coding1.jpeg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health1.jpeg',
        prompt:''
    },
    {
        id:3,
        name:'Creative',
        icon:'/creative.jpeg',
        prompt:''
    },
]
